# Generated by Django 2.0.7 on 2018-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
