# Generated by Django 2.0.7 on 2018-07-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180730_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='add_ons',
            field=models.ManyToManyField(blank=True, related_name='_orderitem_add_ons_+', to='orders.AddOn'),
        ),
    ]
