# Generated by Django 2.0.7 on 2018-07-31 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180731_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.Order'),
        ),
    ]
