# Generated by Django 2.0.7 on 2018-07-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180731_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='add_ons',
            field=models.ManyToManyField(blank=True, null=True, related_name='_orderitem_add_ons_+', to='orders.AddOn'),
        ),
    ]
